Rename statePolytope method from StatePolytope to polymakeStatePolytope
Since StatePolytope now imports gfanInterface, which exports Polyhedra,
and Polyhedra already has a statePolytope method, we would get:

error: assignment to protected built-in global variable 'statePolytope'

Since polymake is used for the computations, the new name seems appropriate.